### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by Zawo1995** [Wentao-Xu/SEEK#1]
Thanks for sharing the code of 'SEEK',I have some issues about the paper itself.

- Is the Figure 1 wrong? 
According to equation(3), the sign of <r_1,h_1,t_0> might be negative  beacause 1+1>=2 and 1 is odd.

- Could you explan why you design 'x+y>=k' to decide the sign, why not only use odd and even of x? 

Looking forward to your response :)

**Comment by Wentao-Xu** [comment]
Thanks for pointing the issues!

- The Figure 1 has a little wrong, we will revise it and upload a new version as soon as possible.

- Only using odd and even of x to decide the sign can not preserve the antisymmetry property. If we set the s_{x,y} to 1 when x is even and -1 while x is odd, when k =2, 
     f_3(h, r, t) = <r_0, h_0, t_0> + <r_0, h_0, t_1> +  <r_0, h_1, t_0> + <r_0, h_1, t_1> - <r_1, h_0, t_0> - <r_1, h_0, t_1> - <r_1, h_1, t_0> - <r_1, h_1, t_1>,
     f_3(t, r, h) = <r_0, t_0, h_0> + <r_0, t_0, h_1> +  <r_0, t_1, h_0> + <r_0, t_1, h_1> - <r_1, t_0, h_0> - <r_1, t_0, h_1> - <r_1, t_1, h_0> - <r_1, t_1, h_1>,
     then f_3(h, r, t) is always equal to f_3(t, r, h) because <a, b, c> = <a, c, b>, thus the function f_3 can not preserve the antisymmetry property in this situation.

**Comment by Zawo1995** [comment]
Thanks, I get it.
If it's convenient, I wonder know how you come up with so ingenious idea about the x+y>=k :)

**Comment by Zawo1995** [comment]
After last issue, I spend a few time thinking about again.
Suppose k=2, according to equation(3) from paper.
f_3(h, r, t) = <r_0, h_0, t_0> + <r_0, h_0, t_1> + <r_0, h_1, t_0> + <r_0, h_1, t_1> + <r_1, h_0, t_0> + <r_1, h_0, t_1> - <r_1, h_1, t_0> - <r_1, h_1, t_1>,
f_3(t, r, h) = <r_0, t_0, h_0> + <r_0, t_0, h_1> + <r_0, t_1, h_0> + <r_0, t_1, h_1> + <r_1, t_0, h_0> + <r_1, t_0, h_1> - <r_1, t_1, h_0> - <r_1, t_1, h_1>,
when r is symmetric, it should have f_3(h, r, t) = f_3(t, r, h), but it seems not equal, 
because left = <r_1, h_0, t_1> - <r_1, h_1, t_0> != <r_1, t_0, h_1> - <r_1, t_1, h_0> = right
Did I forget some conditions?

**Comment by Wentao-Xu** [comment]
Yes, the f_3(h, r, t) != f_3(t, r, h) in this situation. But we use the even part (r_0) to preserve the symmetry and the odd part (r_1) to preserve the antisymmetry, and the even part of f_3(h, r, t) is equal to the even part of f_3(t, r, h). Both of the r_0 and r_1 are learnable parameters.

**Comment by Zawo1995** [comment]
So the problem is to satisfy relation properties, not always.
So my previous idea of only use even and odd gets wrong, because it doesn't satisfy asy relation any time.
Can I understand in this way?

**Comment by Wentao-Xu** [comment]
Yes, exactly.
