### ISSUE TITLE
Is there Python version to Implement your model?

### ISSUE THREAD

**Issue by Excelsiorly** [Wentao-Xu/SEEK#2]
Hi there! I think your work is outstanding and I want to cite your model on my work. And I wonder if there is a python version to implement your model?

Looking forward to your reply.

Best wishes.

**Comment by Wentao-Xu** [comment]
Thank you for your interest in our work. There is no python version at the moment.
If you need to implement the SEEK quickly, you can find a [python version's ComplEx model](https://github.com/facebookresearch/kbc) and modify the scoring function.

**Comment by Excelsiorly** [comment]
Thanks a lot!
