### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by syl072096** [Wentao-Xu/SEEK#3]
请问您是在Windows还是Linux系统里做的这个项目，还有用的C++编译器是啥，谢谢呢

**Comment by Wentao-Xu** [comment]
Hi, I did it on Linux, and it can also run on Windows. The C++ compiler is GCC, and the GCC version needs to higher than 4.8.0 to support C++11.

**Comment by syl072096** [comment]
oh, thank you very much!
